import Head from "next/head";
import Link from "next/link";
import { getSortedPostsData } from "../../lib/posts";

export async function getStaticProps() {
    const allPostsData = getSortedPostsData();
    return {
      props: {
        allPostsData,
      },
    };
  }

  export default function Blog({ allPostsData }) {
    return (
      <>
        <Head>
          <title>Dream Life To-Do App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-gradient-to-tr from-green-300 via-blue-500 to-purple-600">
          <div className="container mx-auto flex flex-col items-center pt-6 min-h-[100vh] gap-y-6">
            <h1 className="text-5xl text-center font-bold text-indigo-900 mb-10">Blog</h1>
            <p className="text-xl text-center text-slate-800 mb-10">Coffee-powered blog entries for maximum productivity☕</p>
            <div className="w-full max-w-3xl">
                {allPostsData.map(({ id, date, title}) => (
                <div key={id} className="sm:flex sm:flex-row xs:flex xs:flex-col justify-between">
                    <Link
                    href={`blog/${id}`}
                    className="text-2xl text-violet-900 font-bold pb-4 inline-block hover:text-violet-700  cursor-pointer"
                    >
                    {title} 
                    </Link>
                    <div className="text-slate-800 pb-4 inline-block">{date}</div>
                </div>
                ))}
            </div>
            <div className="flex flex-row gap-x-4 mt-10 absolute bottom-4">
                <Link href="/" className="hover:text-violet-900">
                Home
                </Link>
                <Link href="/about" className="hover:text-violet-900">
                About
                </Link>
            </div>
          </div>
        </main>
      </>
    );
  }