import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import clock from '../public/clock.svg';

export default function About() {
  return (
    <>
      <Head>
        <title>Dream Life To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>                         
        <main className="bg-gradient-to-tr from-green-300 via-blue-500 to-purple-600">
            <div className="container mx-auto flex flex-col items-center p-6 min-h-[100vh] gap-y-16">
                <h1 className="text-5xl text-center font-bold text-indigo-900 mt-6">
                About this app
                </h1>
                <Image src={clock} className="w-[300px]" alt="clock image" />
                <div className="xl:w-6/12 sm:w-9/12 text-center">
                    <p className="text-lg">
                      When you have a do-to list that&apos;s practical and looks this beautiful, you&apos;ll enjoy checking in with your goals daily. This app will help you create your dream life!
                    </p> 
                </div>
                <div className="flex flex-row gap-x-2">
                    <Link href="/" className="text-lg cursor-pointer hover:text-violet-900">
                    👈 Return to home page
                    </Link>
                </div>
            </div>
        </main>
    </>
  )
}
