import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import productivity from '../public/productivity.svg';

export default function About() {
  return (
    <>
      <Head>
        <title>Dream Life To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>                         
        <main className="bg-gradient-to-tr from-green-300 via-blue-500 to-purple-600">
            <div className="container mx-auto flex flex-col items-center p-2 min-h-[100vh] gap-y-16">
                <h1 className="text-5xl text-center font-bold text-indigo-900 mt-6">
                About this app
                </h1>
                <Image src={productivity} className="w-[300px]" alt="ranking 1st image" />
                <div className="sm:w-6/12 xs:w-full text-center">
                    <p className="text-lg">
                      When you have a do-to list that&apos;s practical and looks this beautiful, you&apos;ll enjoy checking in with your goals daily. This app will help you create your dream life!
                    </p> 
                </div>
                <div className="flex flex-row gap-x-4 absolute bottom-4">
                    <Link href="/" className="hover:text-violet-900">
                    Home
                    </Link>
                    <Link href="/blog" className="hover:text-violet-900">
                    Blog
                    </Link>
                </div>
            </div>
        </main>
    </>
  )
}
