import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Blog() {
  return (
    <>
      <Head>
        <title>Dream Life To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className=" bg-gradient-to-tr from-green-300 via-blue-500 to-purple-600">
            <div className="container mx-auto flex flex-col items-center p-2 min-h-[100vh] gap-y-16">                         
                <h1 className="text-5xl text-center font-bold text-indigo-900 mt-6">
                    Inspiring blog page
                </h1>
                <div className="sm:w-6/12 xs:w-full text-center">
                    <p className="text-lg">
                    Stay tuned for productivity tips that help you achieve your goals!
                    </p> 
                </div>
                <div className="flex flex-row gap-x-4">
                    <Link href="/" className="text-lg cursor-pointer hover:text-violet-900">
                    👈 Return to home page
                    </Link>
                </div>
            </div>
        </main>  
    </>
  )
}
