import Head from 'next/head';
import { authOptions } from "pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth/next";
import { add } from "date-fns";
import { TodoRow } from '../components/TodoRow';
import { AddItem } from '../components/Additem';
import { LogoutButton } from '../components/LogoutButton';


export async function getServerSideProps(context) {
   // 1st we need to fetch a session
   const session = await getServerSession(
    context.req,
    context.res,
    authOptions
  );
    // after checking if we have a session, if we don't, redirect user to home page
    if (!session) {
        return {
          redirect: {
            destination: "/",
            permanent: false,
          },
        };
    }

    const todos = [
        {
            id: "dmoa40s",
            description: "Learn Next.js",
            priority: 5,
            dueDate: `${add(new Date(), {days: 14})}`,
        },
        {
            id: "kdolr6s",
            description: "Go grocery shopping",
            priority: 4,
            dueDate: `${new Date()}`,
        },
        {
            id: "s0mahg32",
            description: "Apply to job",
            priority: 3,
            dueDate: `${add(new Date(), {days: 3})}`,
        },
        {
            id: "39cmabb53",
            description: "Groom the dog",
            priority: 2,
            dueDate: `${add(new Date(), {days: 4})}`,
        },
        {
            id: "dsmc350s",
            description: "Go to gym",
            priority: 1,
            dueDate: `${add(new Date(), {days: 2})}`,
        },
    ];

    return { props: { todos } };
}

  
export default function Dashboard({todos}) {
    console.log(todos);
  return (
    <>
      <Head>
        <title>Dream Life To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>                         
        <main className="bg-zinc-200">
            <div className="container mx-auto flex flex-col p-6 min-h-[100vh] gap-y-6 max-w-4xl">
                <div className="flex flex-row justify-between text-center">
                    <div className="text-5xl font-bold text-slate-700">
                        Your Dream To-dos 🌠
                    </div>
                <div>
                    <LogoutButton />
                    </div>    
                </div>
                <AddItem />
                <div className="overflow-hidden overflow-x-auto rounded-lg border border-violet-900">
                    <table className="table-auto min-w-full divide-y divide-violet-900 text-sm">
                        <thead className="bg-gray-100">
                        <tr>
                            <th className="whitespace-nowrap px-4 py-2 text-left font-medium text-lg text-gray-900">
                            📕 Description
                            </th>
                            <th className="whitespace-nowrap px-4 py-2 text-left font-medium text-lg text-gray-900">
                            🔥 Priority
                            </th>
                            <th className="whitespace-nowrap px-4 py-2 text-left font-medium text-lg text-gray-900">
                            🗓 Due
                            </th>
                        </tr>
                        </thead>
                        <tbody className="divide-y divide-violet-800">
                            {todos.map((todo) => (
                                // <div key={todo.id}>
                                //     {todo.description}
                                // </div>
                                <TodoRow key={todo.id} todo={todo} />
                            ))}
                        </tbody>
                    </table>
                </div>
                <div>
                    <div className="text-2xl">Status</div>
                    <div>You have {todos.length} to-dos on your list!</div>
                </div>
            </div>
        </main>
    </>
  );
}
