import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from "react";
import productivity from '../public/productivity.svg';
import { LoginButton } from '../components/LoginButton';

export default function Home() {
  let localStorageConsent;
  const [cookiesAccepted, setCookiesAccepted] = useState(true);

  useEffect(() => {
    setCookiesAccepted(localStorageConsent);
  }, [localStorageConsent]);

  if (typeof window !== "undefined") {
    localStorageConsent = window.localStorage.getItem("cookies-accepted");
  }

  const acceptCookies = () => {
    localStorageConsent = window.localStorage.setItem("cookies-accepted", true);
    setCookiesAccepted(true);
  };

  return (
    <>
      <Head>
        <title>Dream Life To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="bg-gradient-to-tr from-green-300 via-blue-500 to-purple-600">
            <div className="container mx-auto flex flex-col items-center p-6 min-h-[100vh] gap-y-14">
                <h1 className="text-5xl text-center font-bold text-indigo-900 mt-6">
                Dream To-Dos
                </h1>
                <Image src={productivity} className="w-[300px]" alt="productivity image" />
                <div className="xl:w-6/12 sm:w-9/12 text-center">
                  <p className="text-lg">
                    Your dream life starts with crushing your tomorrow&apos;s goals!
                  </p>
                  <div className="flex flex-row justify-center gap-x-4 mt-4 text-violet-900">
                      <LoginButton />
                  </div>
                </div>
                <div className="flex flex-row gap-x-4">
                  <Link href="/about" className="hover:text-violet-900">
                    About
                  </Link>
                  <Link href="/blog" className="hover:text-violet-900">
                    Blog
                  </Link>
                </div>
                {cookiesAccepted === null && (
                <div className="absolute bottom-0 flex flex-row justify-center text-center bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-4 w-full">
                  Please{" "}
                  <span
                    className="text-violet-900 cursor-pointer hover:text-violet-700 font-bold"
                    onClick={acceptCookies}
                  >
                    &nbsp;accept cookies
                  </span>
                  , we&apos;ll be nice, we promise! 🤭
                </div>
              )}
            </div>
        </main>
    </>
  );
}
